# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
#     - name: Set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
#     - name: Build with Maven
#       run: mvn -B package --file pom.xml
#     - uses: actions/upload-artifact@v2
#       with:
#         path: /home/runner/work/CityWorld/CityWorld/target/
      - name: Build with Maven
        run: mvn package
      - name: Minecraft Custom Tag
        id: mctagcustom
        uses: boyphongsakorn/minecraft-beta-version-style@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
          custom_tag: 5.0.0-beta-${{ steps.mctagcustom.outputs.betaversion }}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/CityWorld-*.jar"
          tag: 5.0.0-beta-${{ steps.mctagcustom.outputs.betaversion }}
          prerelease: true
